<a href="https://colab.research.google.com/github/Parth-Kakdiya-13/TensorFlow/blob/main/One_hot_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
#create some list
some_list = [0,1,2,3]
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specifies custome values for one hot encoder
tf.one_hot(some_list,depth=4,on_value="I love deep learning",off_value="I also like watching movies")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love deep learning', b'I also like watching movies',
        b'I also like watching movies', b'I also like watching movies'],
       [b'I also like watching movies', b'I love deep learning',
        b'I also like watching movies', b'I also like watching movies'],
       [b'I also like watching movies', b'I also like watching movies',
        b'I love deep learning', b'I also like watching movies'],
       [b'I also like watching movies', b'I also like watching movies',
        b'I also like watching movies', b'I love deep learning']],
      dtype=object)>

**Sqaring, log, square root**

---



In [ ]:
# create a tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

**To find the square root, non-int type values are require**

---



---

*italicized text*

In [ ]:
# square root
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

**To find the log, non-int type values are require**

---



In [ ]:
# Find log
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>