<a href="https://colab.research.google.com/github/Parth-Kakdiya-13/TensorFlow/blob/main/variance_and_standardDaviation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

# Create a sample tensor
data = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0])
data2 = tf.constant([1,2,3,4,5])

# Calculate the variance
variance = tf.math.reduce_variance(data)
# data,variance

**in tfp method there are both values work decimals and float vales**

---



In [ ]:
#find variance with tensorflow probability library
import tensorflow_probability as tfp
variance = tfp.stats.variance(data)
variance

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

**in tf.math.reduce_variance and reduce_std mtehod only float values work**

---

we can use type conversion to convert int to float to work with tf.math

In [ ]:
# find standard daviation with tf.math.reduce_std()
# without using float values in this method it throw type error
variance = tf.math.reduce_variance(tf.cast(data2,dtype=tf.float32))
variance

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [ ]:
# Create a new tensor for finding minimum and maximum
tf.random.set_seed(42)
f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# fin the positional maximum value
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index on our largest value position
# f[tf.argmax(f)]

In [ ]:
# find the max value of f
# tf.reduce_max(f)

In [ ]:
# check equality
f[tf.argmax(f)] == tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# findin the min value
tf.reduce_min(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

In [ ]:
# finding the min value using tf.argmin
tf.argmin(f)
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

In [ ]:
# check equality
f[tf.argmin(f)]==tf.reduce_min(f)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# tf.reduce_mean(f)

In [ ]:
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

In [ ]:
# squeezing a tensor(removing all single dimansions)
# creating a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
# squeeze is Removes dimensions of size 1 from the shape of a tensor.
G_squeeze = tf.squeeze(G)
G_squeeze,G_squeeze.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

In [ ]:
# create a list of indeces
some_list = [0,1,2,3]
# One hot encode our list of indeces
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# specifies custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value="I love deep learining",off_value="But it is too hard to learn",indices=[0,1,2,3])

TypeError: Got multiple values for argument 'indices'